-- TODO schema
-- example
-- create table members
-- (
--     id                 bigint primary key      not null auto_increment,
--     name               varchar(50)             not null,
--     created_date       timestamp default now() not null,
--     last_modified_date timestamp
-- );

-- 회원 테이블 생성
CREATE TABLE members (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username          VARCHAR(50)  NOT NULL,
    password          VARCHAR(255) NOT NULL,
    name              VARCHAR(50)  NOT NULL,
    role              VARCHAR(20)  NOT NULL,

    -- BaseEntity 필드
    created_date      TIMESTAMP,
    created_by        VARCHAR(50)  NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by  VARCHAR(50),

    PRIMARY KEY (id),
    CONSTRAINT uk_members_username UNIQUE (username)
);

-- 콘텐츠 테이블 생성
CREATE TABLE contents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title             VARCHAR(100) NOT NULL,
    description       TEXT,
    view_count        BIGINT       NOT NULL,
    member_id         BIGINT       NOT NULL,

    -- BaseEntity 필드
    created_date      TIMESTAMP,
    created_by        VARCHAR(50)  NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by  VARCHAR(50),

    PRIMARY KEY (id)
);

-- 외래 키 제약 조건 추가
ALTER TABLE contents
    ADD CONSTRAINT fk_contents_member
    FOREIGN KEY (member_id) REFERENCES members (id);

-- 인덱스 추가 (Entity의 @Index 반영)
CREATE INDEX idx_contents_id_created_date ON contents (id, created_date DESC);
