## server
server:
  port: 8080
  forward-headers-strategy: native

## spring
spring:
  application:
    name: simple-cms-api
  h2:
    console:
      enabled: on
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/sql/h2-schema.sql
      data-locations: classpath:db/sql/h2-data.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  threads:
    virtual:
      enabled: on


## p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: on

## logging
logging:
  charset:
    console: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  level:
    root: info
    web: info
    com.malgn: debug

## jwt
jwt:
  secret: ${JWT_SECRET:Jiy6bOUQEI9qYCwN1WbvfB554fqHcJR30DAkLdZiT0pWNKcBWDsWg8IMWOiyOVt57WmunUeQs4fcSjcTc1hjSBlULo7PYF4y3QTNPJlUosX75p8pPkAmQpteSRWB926G}
  expiration:
    access: ${ACCESS_TOKEN_EXPIRATION:3600000}
    refresh: ${REFRESH_TOKEN_EXPIRATION:1209600000}

## swagger
springdoc:
  swagger-ui:
    with-credentials: true
    tags-sorter: alpha